### ISSUE TITLE
acme_certificate: recursive_nameservers ignored

### ISSUE THREAD

**Issue by eocern** [vancluever/terraform-provider-acme#104]
I am in a restricted network, I need to set "recursive_nameservers" to our internal DNS but the terraform resource "acme_certificate" keeps on ignoring that recursive_nameservers value I have specified. I see that when error is thrown that it still tried to contact directly the AWS DNS IP's. Even the documentation claims that this should be in dns_challenge block "To override this default behavior, supply the recursive_nameservers to use as a list in host:port form within the dns_challenge block:" but it is not supported there and terraform throws an error - it needs to be set outside the dns_challenge block.
Somehow if I set 
recursive_nameservers = ["8.8.8.8:53"]
then I see that in the error output. Is there some "recursive_nameservers/8.8.8.8:53" leftover hardcoding around ?

**Comment by fabiendelpierre** [comment]
I think I'm having a similar/related issue... I'm running in Azure and landed here by way of [this GitHub issue on the azurerm provider](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6291), but I don't think the issue has anything to do with the azurerm provider.

My code looks like this and I'm running TF 0.12.24 through Terraform Enterprise.

```
provider "acme" {
  version = "~> 1.0"
  server_url = "https://acme-staging-v02.api.letsencrypt.org/directory"
}

provider "tls" {
  version = "~> 2.1"
}

resource "tls_private_key" "infra_sandbox" {
  algorithm = "RSA"
}

resource "acme_registration" "infra_sandbox" {
  account_key_pem = tls_private_key.infra_sandbox.private_key_pem
  email_address   = "user@email.com"
}

resource "acme_certificate" "infra_sandbox" {
  account_key_pem           = acme_registration.infra_sandbox.account_key_pem
  common_name               = "example.com"
  subject_alternative_names = ["*.example.com"]

  recursive_nameservers = ["1.1.1.1:53"]

  dns_challenge {
    provider = "azure"
    config = {
      AZURE_RESOURCE_GROUP = "my-azure-resource-group"
    }
  }
}
```

This partially works: I can see that the `_acme-challenge` TXT record gets added to my Azure DNS zone, so I was hopeful that this would work, but alas... I get this error:

```
Error: error creating certificate: acme: Error -> One or more domains had a problem:
[example.com] time limit exceeded: last error: read udp 172.17.0.21:47434->192.100.102.4:53: i/o timeout
```

Sometimes I only get one error line (as shown above), sometimes two lines (one for example.com and the other for *.example.com). 

I get the same behavior whether I include the `recursive_nameservers` argument or not.

The 172.17.0.21 IP address is from a Docker network in which TFE jobs run, and 192.100.102.4 is a Microsoft-owned IP address, to which I can connect over UDP port 53, so I don't know why the connection is timing out. 

I can't test the same code directly from my laptop because I'm using Azure for the DNS, which queries the local 169.254.169.254 metadata endpoint, so all I can do is basic network connectivity tests.

Anyway, I would think that setting `recursive_nameservers` would force things to go through the specified name server(s) instead of the default Azure resolvers, but that doesn't appear to be the case unless I'm misunderstanding what this setting is supposed to do.

**Comment by fabiendelpierre** [comment]
Any chance that somebody might look at this issue?

I seem to be the victim of a peculiar manifestation of the issue specific to Azure, but the overarching issue seems to be indeed that the `recursive_nameservers` argument is ignored.

Like I mentioned in my previous comment, I'm using Terraform Enterprise and battling this issue, there doesn't seem to be a solution no matter what I do.

I did additional troubleshooting today with `recursive_nameservers = ["168.63.129.16:53"]` (this IP is a virtual IP available to all Azure VMs for DNS resolution among other things)... TFE runs 100% on containers, so when you run a `tf apply`, it runs that inside of a container. Since this container lasts for a few minutes while waiting for the DNS challenge, I managed to log in to it and installed `dig` to do some checks and see if I could retrieve the _acme-challenge TXT record. And it worked fine!

```
# dig txt _acme-challenge.mydomain.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> txt _acme-challenge.mydomain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52895
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
; OPT=65436: 5d 75 b6 9f bd 1c b2 42 b2 59 ae 41 45 55 e2 b1 ("]u.....B.Y.AEU..")
;; QUESTION SECTION:
;_acme-challenge.mydomain.com. IN TXT

;; ANSWER SECTION:
_acme-challenge.mydomain.com. 60 IN TXT "Nx3N8shWkrLw82YwL3bcTyNQ-mPaLZHU-NlFziaPfqk"
_acme-challenge.mydomain.com. 60 IN TXT "tObeBagcC4HAiPXNjbFvgKsn613dQvjtiUDjmKoAnDk"

;; Query time: 14 msec
;; SERVER: 168.63.129.16#53(168.63.129.16)
;; WHEN: Tue May 05 22:32:53 UTC 2020
;; MSG SIZE  rcvd: 208
```

Note that, 169.63.129.16 is the default DNS resolver in all Azure VMs. Your docs ([link](https://www.terraform.io/docs/providers/acme/r/certificate.html#manually-specifying-recursive-nameservers-for-propagation-checks)) say "The ACME provider will normally use your system-configured DNS resolvers to check for propagation of the TXT records before proceeding with the certificate request."

This does NOT appear to be the case, because the error returned by TF is as follows:

```
Error: error creating certificate: acme: Error -> One or more domains had a problem:
[*.mydomain.com] time limit exceeded: last error: read udp 172.17.0.21:37689->192.100.103.4:53: i/o timeout
```

192.100.103.4 in the output above is some Microsoft nameserver that I've tested connecting to, and I've found that it doesn't always work. The error above suggests it timed out trying to connect to it.

Interestingly, my cert request was for a cert with two aliases. Sometimes the error I get says the request timed out for both certs, sometimes only for one (as above).

But how are you getting this 192.100.103.4? I figured that out:

```
$ dig +short ns mydomain.com
ns4-04.azure-dns.info.
ns3-04.azure-dns.org.
ns2-04.azure-dns.net.
ns1-04.azure-dns.com.
$ dig +short ns4-04.azure-dns.info
13.107.24.4
192.100.103.4
```

So that's where that IP address came from... but why are you using it for the DNS challenge instead of the system default? In Azure, the default is 168.63.129.16, and in AWS it would be the [AmazonProvidedDNS](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html#AmazonDNS) resolver? I'm not a GoLang expert but I traced through your code a bit and found this: https://github.com/terraform-providers/terraform-provider-acme/blob/master/vendor/github.com/go-acme/lego/v3/challenge/dns01/precheck.go#L71-L93
It looks like this goes through the authoritative nameservers for my domain and checks that the DNS-01 challenge records are present on all of them... but when you can't connect to one of them, as appears to be the case here, you don't fail gracefully.

So I'm wondering if your DNS check could be set up so that you tolerate timeouts from some of the authoritative nameservers as long as at least some of them have responded.

Or allow control of the [requireCompletePropagation](https://github.com/terraform-providers/terraform-provider-acme/blob/master/vendor/github.com/go-acme/lego/v3/challenge/dns01/precheck.go#L50-L55) parameter, which appears to default to `true` here and is probably causing this issue.

Or better yet, and going back to the original issue... since we're setting `recursive_nameservers`, why not skip the check against the authoritative DNS servers when this parameter is set?

Please please please help... am I doing something wrong perhaps? I don't think so, but do tell. I feel like I'm so close and yet so far, it's driving me bonkers. Thank you.

**Comment by fabiendelpierre** [comment]
FWIW I've implemented [acme.sh](https://github.com/acmesh-official/acme.sh) to work around this issue. It's not ideal for a few reasons, but it works for my specific use case.

**Comment by DarkMukke** [comment]
The documentation reads : " set it in the dns_challenge block", but the example shows it in the resource block. Maybe the `recursive_nameservers` are per `dns_challenge` block ?

**Comment by vancluever** [comment]
Hey @fabiendelpierre: 

> I'm not a GoLang expert but I traced through your code a bit and found [this](https://github.com/terraform-providers/terraform-provider-acme/blob/078933f0b7708d3b42979933e3cef3fddcbd7fc1/vendor/github.com/go-acme/lego/v3/challenge/dns01/precheck.go#L71-L93)

That code is actually part of the ACME library we use, [lego](https://github.com/go-acme/lego). Additionally, the function does source from the system default DNS nameservers, as seen [here](https://github.com/terraform-providers/terraform-provider-acme/blob/405c13920d4a34a12522f8314eb4ff5ee6208887/vendor/github.com/go-acme/lego/v3/challenge/dns01/nameserver.go#L28-L29). The `getNameservers` function also will give you more of an idea how non-default nameservers are read from the configuration.

> why are you using it for the DNS challenge instead of the system default?

A domain's nameservers are indeed queried to walk the DNS namespace to the discover the correct zone. This important for things like subdomains where DNS may be delegated. This is separate from the propagation check though.


Regarding the core of the issue, DNS propagation checks _should_ be happening with the configured `recursive_nameservers`. This will happen after the addition of the challenge record to all providers.

You should be able to check this by running Terraform with `TF_LOG=debug` and looking for the line found [here](https://github.com/terraform-providers/terraform-provider-acme/blob/405c13920d4a34a12522f8314eb4ff5ee6208887/vendor/github.com/go-acme/lego/v3/challenge/dns01/dns_challenge.go#L127). It will display the DNS servers being used. Can you run this, check, and send the results along?

Thanks!

**Comment by fabiendelpierre** [comment]
Hi there, thanks for responding.

You're right, it uses the DNS resolver I set, here are the relevant lines that prove it:

```
2020-05-11T17:17:32.543Z [DEBUG] plugin.terraform-provider-acme_v1.5.0_x4: 2020/05/11 17:17:32 [DEBUG] lego: [*.mydomain.com] acme: Checking DNS record propagation using [168.63.129.16:53]
2020-05-11T17:19:32.824Z [DEBUG] plugin.terraform-provider-acme_v1.5.0_x4: 2020/05/11 17:19:32 [DEBUG] lego: [mydomain.com] acme: Checking DNS record propagation using [168.63.129.16:53]
```

Sadly the provider still queries the zone's authoritative nameservers and that appears to be the part where everything fails.

**Comment by fabiendelpierre** [comment]
Alright, happy to report I've fixed my problem by setting a higher propagation timeout. TF returned successfully after 20 minutes. I set a fairly high polling interval of 1m, maybe that contributed to it taking so long, I will keep testing, but super pumped that this is working. I assumed the defaults were fine all along but need to get into the mindset that nothing is fine in Azure, since I'm forced to use it.

That being said, I realize that I may have veered off topic from @eocern's original report so I yield back to them in case their issue is different under the hood and please don't close this issue just because my problem is apparently fixed :)

**Comment by vancluever** [comment]
Thanks @fabiendelpierre. That's indeed strange, I'll try and get a repro going when I got some free cycles here.

**Comment by vancluever** [comment]
At this point in time I think I'm going to leave this. I think the advice that I put into this issue earlier should apply to the original issue. If this is still an ongoing thing, please open a new issue!
