### ISSUE TITLE
Fix on go-acme/lego for Designate

### ISSUE THREAD

**Issue by skatsaounis** [vancluever/terraform-provider-acme#128]
Hi @vancluever,

While working with your awesome provider in my OpenStack deployment I found out a bug regarding Designate, which is DNSaaS component of OpenStack. Since the `go-acme/lego` is going to include it in its 4.1 release I am opening this issue so as to help do not miss this fix.

https://github.com/go-acme/lego/pull/1279

Of course, this is going to delay coming to your provider but I hope it will at some point. Until then, I will use the `go-acme/lego` as cli, since I have no other alternative.

Kind regards,
Stamatis

**Comment by vancluever** [comment]
@skatsaounis awesome, thanks for this! I'll just keep this open in the tracker until this is resolved. Will keep an eye out!

**Comment by vancluever** [comment]
@skatsaounis happy to say that v4.1.0 is out now and will be in the next release. 👍

**Comment by skatsaounis** [comment]
@vancluever That's awesome news! Since I am a little bit confused I want to ask you. What is happening with the release of your provider? I noticed that it was recently moved in your repository and that the latest release downloaded by Terraform does not include other updates as well. For example, support of `OS_CLOUD` for Designate.

Can you shed some light and/or even inform me when is this going to be available?

Once again, thank you very much 😃

**Comment by vancluever** [comment]
@skatsaounis since it's not my day job to update the provider, progress has been slow. But what is going on:

* I'm working on cleaning/updating this repo to add in the latest version of ACME and resolve as many bugs/feature requests as possible.
* After that I'm updating to repo to use the latest TF SDK.
* After that I'm fixing the docs to work with the new portable update format.
* After that I will be working on building the provider and pushing it to the registry.

Cheers!
