### ISSUE TITLE
more robust to network errors

### ISSUE THREAD

**Issue by andyli** [vancluever/terraform-provider-acme#137]
I got several random network errors today, which disappear in retries.

Got 2 times the error as follow:
```
Error: get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get "https://acme-v02.api.letsencrypt.org/directory": net/http: TLS handshake timeout
```

Another error I got in another `terraform apply`:
```
Error: Post "https://acme-v02.api.letsencrypt.org/acme/new-acct": net/http: timeout awaiting response headers
```

It would be great if the provider can automatically retry failed network requests.

**Comment by vancluever** [comment]
Hey @andyli, thanks for the suggestion. I suspect that retries may be hard to test and confirm that they are working properly due to the sporadic nature of such things, and the possible difficulty in determining what requests are actually safe to retry.

I think this would be something that would be lego's domain to really work on, so I'd expect any work to support that to be done there, but I'd say that the other aforementioned issues remain. I'd expect that retries may be better implemented at the Terraform level via possibly retrying at the CI level, where subsequent Terraform runs can work off any partially completed state to finish applying any resources still outstanding due to the failure.

Regardless this data is good data to have in the event that we want to build out something like this in the future, so thank you!
