### ISSUE TITLE
Add support on reusing key (e.g. --reuse-key flag in acme.sh)

### ISSUE THREAD

**Issue by Jyrno42** [vancluever/terraform-provider-acme#227]
It seems that currently it is not possible to reuse they existing key when doing renewals. This functionality was added to acme in [this commit](https://github.com/go-acme/lego/commit/db1a519684cfaef862c4aa0345b341c9dae49e45) and certbot itself uses it when --reuse-key flag is provided.

I guess to support this in this provider we need to add a new parameter to the `client.Certificate.Obtain` call named `PrivateKey` and provide the currently existing private key value to this field.

Note: I can submit a PR myself if someone points me to the correct way of loading the existing private key.

**Comment by vancluever** [comment]
Hey @Jyrno42 thanks for the heads up. I think this may just be for the ACME CLI tooling or what not, because `Renew` already has support for this implicitly (see [here](https://github.com/go-acme/lego/blob/v4.6.0/certificate/certificates.go#L391-L401)).

We use Renew for certificate renewal in our update method, as seen [here](https://github.com/vancluever/terraform-provider-acme/blob/3eef41a371d1d5d3039ec9a45b31ad68d81aada0/acme/resource_acme_certificate.go#L402-L411).

Are you having issues getting certificate renewals to use the same private key?

Thanks!

**Comment by vancluever** [comment]
Hey @Jyrno42 just going to close this due to inactivity. If you still feel like it needs attention feel free to reply.

Thanks!
