### ISSUE TITLE
ACME certificates using webroot challenge

### ISSUE THREAD

**Issue by carobaldino** [vancluever/terraform-provider-acme#228]
Hello everyone!

I’m trying to automate certificate’s generation using `webroot challenge`

The example given in the documentation is the following:
```terrafrom
resource "acme_certificate" "certificate" {
  #...


  # Use http_webroot_challenge to publish a record to a location 
  # on the file system. The record is  published
  # to DIRECTORY/.well-known/acme-challenge/. The resource will request an HTTP-01
  # challenge for which an out-of-band process must use this data to answer.
  
  http_webroot_challenge {
    directory = "/a/webserver/path"
  }

  #...
}
```

I don’t understand where the records or certs are going to be saved when the challenge occurs, cause I clearly don’t want them to be saved in my local machine from where I run Terrafrom, I want them to be saved in a VM of my cloud provider (Digital Ocean) but the resource “acme_certificate” does not give me any option or configuration to point or select the VM I want.

I saw on the internet that you can access the certificate through its attribute:
```
acme_certificate.certificate
acme_certificate.certificate.certificate_pem
acme_certificate.certificate.issuer_pem
```

But what happen to the `directory` attribute used in the `http_webroot_challenge` ? 

Could anyone bring an example?

Thank you in advance,

C

**Comment by vancluever** [comment]
@carobaldino sorry, but we don't support what you're looking for in the webroot challenge. As mentioned by the warning at the top of the [HTTP challenge types section](https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#using-http-and-tls-challenges), these types are not suitable unless you can actually direct traffic to the machine running Terraform.

I'd imagine you could implement some sort of workaround to ship the challenge data to a place where you can serve it, but I would not recommend it because it would probably be convoluted and we definitely would not have an example of it. Sounds like DNS challenges would be best suited for you.

Thanks!

**Comment by vancluever** [comment]
PS: To answer your question, the webroort challenge basically ships the challenge data to a local directory; you would then serve the data in that directory with an external HTTP server.
