### ISSUE TITLE
PFX Certificate incompatible with Palo Alto

### ISSUE THREAD

**Issue by jdelforno** [vancluever/terraform-provider-acme#254]
Greetings,

When attempting to use a LetsEncrypt certificate provided by acme_certificate, the certificate is incompatible with PANOS.

Attempting to use a PEM file, requires the use of a key and a passphrase associated with said key, which doesn't exist, preventing the use of the PEM file. 

I've been able to import the .pfx file into my local certificate store and then re-export it - it's 2KB smaller - which is then acceptable to PANOS.

I'm unsure as to why PANOS is  so picky but the only thing I can think of is the base64  encoding.

**Comment by jdelforno** [comment]
Confirmed that I can output the pfx via 
`resource "local_file" "foobar" {
   filename       = "./foobar.pfx"
  content_base64 = acme_certificate.cert.certificate_p12
}`

And then upload the certificate into PANOS. Attempting to add the file directly via panos_certificate_import, fails. 

I'm wondering if the issue is related to this: https://github.com/hashicorp/terraform/issues/25777

**Comment by jdelforno** [comment]
Thanks @vancluever I gave the base64decode a shot when passing the the argument and received the same issue unfortunately.

I'm hoping the PANOS provider will be updated to accept base64 encoded certs soon(tm)

**Comment by vancluever** [comment]
@jdelforno I did notice that the PANOS provider uses a different argument for actually accepting "stream" data instead of a file. I guess you tried using the [`certificate`](https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs/resources/certificate_import#certificate) parameter instead of [`certificate_filename`](https://registry.terraform.io/providers/PaloAltoNetworks/panos/latest/docs/resources/certificate_import#certificate_filename)?

**Comment by jdelforno** [comment]
I tried both at the time, in the end, I switched over my certificate provider and used the PEM block  instead  and it worked first time =(

**Comment by vancluever** [comment]
@jdelforno when you say "certificate provider", what are you referring to? Are you still using the ACME provider?
