### ISSUE TITLE
Maybe enhance the docs to mention the use of lego requires internet egress access even if it uses DNS challenge

### ISSUE THREAD

**Issue by xynova** [vancluever/terraform-provider-acme#274]
It would be maybe a good addition to write a paragraph in the docs about the need for internet egress access requirement when using this provider because of how the lego library works

https://github.com/go-acme/lego/issues/1818

We spent a bit of time trying to figure out what was going on because the debug logs dont really point to DNS not being reachable and the errors don't mention it either.

**Comment by vancluever** [comment]
Fixed in 670082f4

@xynova you might also want to check the full [about DNS propagation checks](https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#about-dns-propagation-checks) section which has information about this and what to do in air-gapped scenarios. I've added some extra callout stuff there but the current docs have details about what to expect and what you can do that should address this.
