### ISSUE TITLE
Certificate renovation

### ISSUE THREAD

**Issue by guillermocol** [vancluever/terraform-provider-acme#297]
Hello,

We have the question in regards to the use of these resources, lets say that we have created the acm certificate and is imported to ACM after being run the resources of terraform  for the letsencrypt certificate usage.
If in the future we run the terraform plan one more time to do updates of the platform is going to recreate or renew this imported certificate every time? Or terraform will understand that is there already created?

We have got this doubt after trying to go deeper to understand how the go code works for this process to know if it is doing the renovation or not. 

Source of information: https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#using-dns-challenges

Looking forwards to hearing your thoughts,
Thank you for your help,

**Comment by vancluever** [comment]
Hey @guillermocol DNS challenges aren't what controls certificate renewal, it's the [`min_days_remaining`](https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#min_days_remaining) argument. When the certificate expiry has less time remaining than what is in  this value, a renewal is triggered through a resource update.

I did actually answer a related question fairly recently in https://github.com/vancluever/terraform-provider-acme/issues/289.

Otherwise the certificate should not be touched.

Hope that helps!
