### ISSUE TITLE
Question: Is it possible to automate the renewal process e.g. with Lambda? How?

### ISSUE THREAD

**Issue by sherifkayad** [vancluever/terraform-provider-acme#300]
Hello 👋 .. Thanks for this great provider! I read through the docs of the `acme_certificate` resource and I understood that certificate renewals can be performed with Terraform plan / apply e.g. short before the expiry. Was just wondering is there maybe a way to handle the renewal process with a more automated fashion e.g. without having to run plan / apply? Let's say using a Lambda function or so?

Do you have any recommendations here?

Thanks.

**Comment by vancluever** [comment]
@sherifkayad best thing I could think of here would be a scheduled lambda that did the Terraform run for you, or possibly checked your certificates and then kicked off a TF run somewhere where it would be more visible, such as [Terraform Cloud](https://developer.hashicorp.com/terraform/cloud-docs).

Note that if you manage the certificates in Terraform, you should renew them in Terraform as well, otherwise you risk resource drift which could create an unstable Terraform state that could cause service issues with future plans/applies.

Hope this helps!
