### ISSUE TITLE
Terraform Destroy is causing error

### ISSUE THREAD

**Issue by agarwalmayank32** [vancluever/terraform-provider-acme#336]
When I am trying to delete all my resources using `terraform destroy`, I am getting an error **"acme: error: 403 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:unauthorized :: An account with the provided public key exists but is deactivated"**. I am deleting it as I want to create a new account with new certificate. But while creating new certificate also I am getting the same error. Please help

**Comment by vancluever** [comment]
@agarwalmayank32 this would be caused by the deactivation of the account outside of the lifecycle of the `acme_registration` resource (or some sort of situation with ultimately the same effect).

There have been different times in the lifetime of this provider where I've reviewed whether or not it would be proper to implement some degree of idempotency in the delete process to account for this (meaning that we just drop the result on the floor and consider the resource deleted if the account is deactivated on destroy). I've been hesitant in the past to in the detection that we use in the refresh process here, but I might come back to this and review it again.

For now what you will need to do is just re-do the operation with a fresh state.

Thanks!

**Comment by agarwalmayank32** [comment]
Thank you @vancluever for this quick response. I have one more query regarding this. I am destroying my `tls_private_key` and recreating it. After that, I am trying to again do `acme_registration` but I am still getting the same error. So should I completely delete my state file and recreate everything or is there any other shortcut to recreate `tls_private_key` so that I don't get the error when creating the acme certificate?

**Comment by vancluever** [comment]
@agarwalmayank32 if destroying the `tls_private_key` resource has meant not actually cycling the private key itself, then there's a problem there for sure - not too sure what it would be on this side without looking at your configuration and state more, but something is keeping the `tls_private_key` resource from being completely removed. Is it possible that there is some sort of intermediary step that is retaining the old private key?

Feel free to post your config if that helps (make sure to sanitize it of identifiable information of course).

Thanks!

**Comment by agarwalmayank32** [comment]
My TLS Private key and ACME code are below. I am keeping my code as simple as possible to not retain old private key. My problem got solved with the state file deletion. 

```bash
resource "tls_private_key" "ssl_private_key" {
  algorithm = "RSA"
}

resource "acme_registration" "acme_account_reg" {
  account_key_pem = tls_private_key.ssl_private_key.private_key_pem
  email_address   = var.email_address
}

resource "acme_certificate" "ssl_certificate" {
  account_key_pem           = acme_registration.acme_account_reg.account_key_pem
  common_name               = var.domain
  subject_alternative_names = ["www.${var.domain}"]

  recursive_nameservers        = ["8.8.8.8:53"]
  disable_complete_propagation = true

  dns_challenge {
    provider = "route53"

    config = {
      AWS_ACCESS_KEY_ID     = var.aws_access_key
      AWS_SECRET_ACCESS_KEY = var.aws_secret_key
    }
  }
 }
}

**Comment by vancluever** [comment]
@agarwalmayank32 glad it got resolved! Yeah not too sure why the old key was sticking around - you've set up the references correctly and `account_key_pem` is `ForceNew`. So not too sure what would be going on there!
