### ISSUE TITLE
On resource rename: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by SinnySupernova** [vancluever/terraform-provider-acme#374]
Before applying terraform, I renamed the acme registration resource and it produced the following error on destroy:

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to acme_registration.reg, provider "provider[\"registry.terraform.io/vancluever/acme\"]" produced
│ an unexpected new value: Root object was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

Subsequent attempt to apply resulted in the following error: `Error: acme: error: 403 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:unauthorized :: An account with the provided public key exists but is deactivated`. I can assume that it tried to reuse the old private key for a new account and that failed. 

I was able to move forward after forcing terraform to recreate the pk, but the problem still exists.

**Comment by vancluever** [comment]
@SinnySupernova:

> Before applying terraform, I renamed the acme registration resource and it produced the following error on destroy:

Do you mean you just renamed the resource and ran `terraform apply`, e.g. you're expecting a destroy since the named resource no longer exists in config?

> I can assume that it tried to reuse the old private key for a new account and that failed.

If that's the case, I'm not too sure why this happened in the first place. A cursory glance as to why this error happens would indicate issues with the provider reporting the presence of the resource, but if you're seeing it on subsequent applies, then that sounds like a one-time thing.

> I was able to move forward after forcing terraform to recreate the pk, but the problem still exists.

When you say that the problem still exists, do you mean you're able to reliably reproduce it?

**Comment by vancluever** [comment]
@SinnySupernova I actually was able to get a proper repro myself, so no worries on this one! I'll get it looked into. Thanks!

**Comment by vancluever** [comment]
Oh also @SinnySupernova, you may have to cycle the private key as that is provided externally and that's probably the real reason you're getting the "deactivated private key" error. That's being tracked in #285.

**Comment by vancluever** [comment]
@SinnySupernova this will be closed here shortly as completed. Watch #285 for updates for credential rotation. Thanks!
