### ISSUE TITLE
azuredns: could not find zone (from discovery)

### ISSUE THREAD

**Issue by cschipper1** [vancluever/terraform-provider-acme#428]
Cert renew is not working anymore in the latest version 2.25, we got the error below:

│ Error: error: one or more domains had a problem:
│ [*.<domain_name>] [*.<domain_name>] acme: error presenting token: 2 errors occurred:
│ 	* rpc error: code = Unknown desc = azuredns: could not find zone (from discovery): <domain_name>
│ 	* error encountered while presenting token for DNS challenge: rpc error: code = Unknown desc = azuredns: could not find zone (from discovery): <domain_name>

We tested with lego with the same credentials and dns zone and then a new certificate request is working.

**Comment by cschipper1** [comment]
We are running the code below in a pipeline on a build agent and it was working, now with a renewal due it gives the error below. Credentials etc are not changed. 

I tested the manual request with lego only on a different machine. 

Terraform provider:
 acme = {
      source  = "vancluever/acme"
      version = "2.25.0"
    }

Terraform code:
resource "tls_private_key" "private_key" {
  algorithm = "RSA"
}

resource "acme_registration" "reg" {
  account_key_pem = tls_private_key.private_key.private_key_pem
  email_address   = x
}

resource "acme_certificate" "certificate" {
  account_key_pem           = acme_registration.reg.account_key_pem
  common_name               = "*.${local.dns_zone_name}"
  subject_alternative_names = [local.dns_zone_name]
  certificate_p12_password  = random_password.certpassword.result
  min_days_remaining        = 30

  dns_challenge {
    provider = "azuredns"
    config = {
      AZURE_CLIENT_ID           = x
      AZURE_CLIENT_SECRET       = x
      AZURE_TENANT_ID           = x
      AZURE_ENVIRONMENT         = "public"
      AZURE_PROPAGATION_TIMEOUT = 120
      AZURE_POLLING_INTERVAL    = 10
      AZURE_SUBSCRIPTION_ID     = x
      AZURE_RESOURCE_GROUP      = x
      AZURE_ZONE_NAME           = local.dns_zone_name
    }
  }
}

**Comment by vancluever** [comment]
@cschipper1 please try running Terraform at the same place you're running lego and see what you get. There could be differences in configuration between your build pipeline system and your local machine.

Nothing looks out of place with your config, but also I don't use Azure so it will be difficult for me to reproduce.

**Comment by cschipper1** [comment]
It is working on another machine, so you can close it. If you have any idea to get more logs or a more useful error or debugging info please let me know to further troubleshoot it. Thanks for the quick replies!

**Comment by cschipper1** [comment]
One more question: will the AZURE_CLIENT_ID in the config block override the env variables ARM_CLIENT_ID?

**Comment by vancluever** [comment]
@cschipper1 glad you got it worked out!

**Comment by kjetilcapgemini** [comment]
Need some help on this one. I get the same error message:
│ Error: error: one or more domains had a problem:
│ [.<domain_name>] [.<domain_name>] acme: error presenting token: 2 errors occurred:
│ * rpc error: code = Unknown desc = azuredns: could not find zone (from discovery): <domain_name>
│ * error encountered while presenting token for DNS challenge: rpc error: code = Unknown desc = azuredns: could not find zone (from discovery): <domain_name>

My dns_challenge config block:
dns_challenge {
    provider = "azuredns"
    config = {
      AZURE_AUTH_METHOD     = "env"
      AZURE_ENVIRONMENT     = "public"
      AZURE_CLIENT_ID       = data.azurerm_client_config.current.client_id
      AZURE_SUBSCRIPTION_ID = "11111111-1111-1111-1111-111111111111"
      AZURE_TENANT_ID       = data.azurerm_client_config.current.tenant_id
      AZURE_RESOURCE_GROUP  = data.azurerm_resource_group.rg.name
      AZURE_ZONE_NAME       = "domain.com"
      AZURE_TTL             = 300
    }
  }

The terraform statefile is in a different subscription than where the dns zones is hosted.
Running an Azure devops yaml pipeline with the following env: config in the apply task:
env:
 ARM_USE_AZUREAD: true
 ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

The service principal has contributor and read on subscription level, dns zone administrator on resource group level.

Regards
Kjetil

**Comment by vancluever** [comment]
@stdedos when you say "more visible" what are you specifically referring to? Can you let me know what part is not exactly obvious to you? There are some things that I think could be done to improve things here but the core error is probably something we're not going to do anything about (zone discovery issues).

Thanks!

**Comment by stdedos** [comment]
"In config, please avoid setting `AZURE_SUBSCRIPTION_ID` and prefer `ARM_SUBSCRIPTION_ID`" and/or "Set `ARM_SUBSCRIPTION_ID = ""` before setting `AZURE_SUBSCRIPTION_ID`" in case your Terraform azurerm authentication is in a separate subscription than your DNS Zone is?

I don't know - anything that would help anyone seeing this known issue on https://registry.terraform.io/providers/vancluever/acme/latest/docs/guides/dns-providers-azuredns#argument-reference and avoid them banging their heads "why this doesn't work - I am SURE I gave the correct credentials"

**Comment by vancluever** [comment]
@stdedos hmm, this is a different thing than what I was thinking; general error cleanup is more what I was getting at, which has been an issue since we transitioned to a sub-plugin based architecture a few years ago.

I do get the confusion you're referring to though. Incidentally, credential conflict is one of the concerns that kept the provider was initially rejected for being a core provider way back in 2016; while it largely seems to have not been an issue in the long run, I'm sure it's caused a problem once or twice. Popular providers like Azure probably see the issue exacerbated more than others.

We *do* have a section on this in the main `acme_certificate` documentation, unfortunately it's buried in https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#argument-reference just due to age, in addition to the fact that the registry's documentation generator does not convert the heading to a link.

I'll look at surfacing these docs better in a future version, and keep any way we can improve the error messages in mind - this is something that I don't really want to make exceptions for too much, given that the errors ultimately come from lego, but if there's anything easy that can be done I'm definitely not against it.

Thanks!

**Comment by stdedos** [comment]
> We _do_ have a section on this in the main `acme_certificate` documentation, unfortunately it's buried in https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate#argument-reference just due to age, in addition to the fact that the registry's documentation generator does not convert the heading to a link.

Would you mind being a bit more specific? 😅 I tried to read, but it's too big and I don't know to what **exactly** you are referring to

> I'll look at surfacing these docs better in a future version, and keep any way we can improve the error messages in mind - this is something that I don't really want to make exceptions for too much, given that the errors ultimately come from lego, but if there's anything easy that can be done I'm definitely not against it.

I get it ... you cannot make miracles or "overstep" your boundaries. And neither lego can do something about it (https://github.com/go-acme/lego/discussions/2960).

I get both of you guys (in theory), and I understand you are not ... actively trying to do negatively by the users 😅 

And I am "just a script-kiddie user" - so "I don't even understand what is happening exactly" (although I suspect / I am fairly sure that "it's just Azure's inability to provide error messages")

**Comment by vancluever** [comment]
> Would you mind being a bit more specific? 😅 I tried to read, but it's too big and I don't know to what **exactly** you are referring to

It's the section titled "Relation to Terraform provider configuration". Basically just a note to make sure to be cognizant of possible conflicts with other commonly used cloud providers (such as AWS).

> I get it ... you cannot make miracles or "overstep" your boundaries. And neither lego can do something about it ([go-acme/lego#2960](https://github.com/go-acme/lego/discussions/2960)).
> 
> I get both of you guys (in theory), and I understand you are not ... actively trying to do negatively by the users 😅
> 
> And I am "just a script-kiddie user" - so "I don't even understand what is happening exactly" (although I suspect / I am fairly sure that "it's just Azure's inability to provide error messages")

Not necessarily - I suspect the answer is more complicated. If I've understood the issue right and the there indeed is a credential conflict, the DNS provider is likely having trouble "seeing" the zone because of the fact that it might be connecting using the credentials for a different identity that does not have the necessary permission, which leads to an error that does not necessarily tell you what the root cause is, just what the immediate issue is.

It's one of those conundrums with regards to striking a balance between extremely lengthy error messages, and more terse ones. Terse is generally more favored, leading to the user having to do some work to establish root cause.

With all of this said - I think I understand the confusion now with regards to your original request (extra docs in the Azure provider) - I'll see if we can add something to the documentation around where we document the aliasing behavior (that's the section labeled "The following variables are Terraform-specific aliases...", in https://registry.terraform.io/providers/vancluever/acme/latest/docs/guides/dns-providers-azuredns#argument-reference) to keep folks that need to separate credentials from footgunning themselves here.

Thanks!

**Comment by vancluever** [comment]
@stdedos hopefully #583 should help clear the air! This will be released next release (not yet, but whenever we push a new one - lego update, security update, or other features).

**Comment by stdedos** [comment]
> It's the section titled "Relation to Terraform provider configuration". Basically just a note to make sure to be cognizant of possible conflicts with other commonly used cloud providers (such as AWS).

In retrospective, this is clear. _In retrospective_, though 😅 
A "clear" example of FAFOs that didn't work would be "so much more understandable"

> Not necessarily - I suspect the answer is more complicated. If I've understood the issue right and the there indeed is a credential conflict, the DNS provider is likely having trouble "seeing" the zone because of the fact that it might be connecting using the credentials for a different identity that does not have the necessary permission

That is precisely my question: **Which** identity is ACME using?? "The thing" that's running my Terraform provisioning has **so many** permissions. Like **much** more than I do. If I "steal" its credentials, and "re-point" it to the correct subscription, "it just works". I even force-gave "the thing" permissions to access the correct DNS zone etc - it didn't help
(... "the thing", though, is at least somewhat hacky though, with poor monitoring and observability [from where I am sitting])

`azure` (and *not* `azuredns`) did me the favor of telling me "subscription A, zone B: not found". `azuredns` just says "not found". It is **a very valid assumption** that, if you are directly using the library _of course you know which credentials and subscription you've pointed it to_. But not via a Terraform orchestrator, via a Terraform provider, via Lego - to end up using AzureSDK .

> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/133706?u=c19422ae9646a1a58b9c62a57a2143e62c5f8001&amp;v=4&amp;size=48">@stdedos](https://github.com/stdedos) hopefully [#583](https://github.com/vancluever/terraform-provider-acme/pull/583) should help clear the air!

It does 😊 It **still** took me some time to read it through and "understand" it - but yes, it is next to this block - which makes it obvious to consider

Thank you ❤️

**Comment by vancluever** [comment]
@stdedos no problem! Just in closing it might be useful for you to slice off the certificate stuff into its own TF workspace in your infra and just pass stuff over through outputs, data sources, etc. That way you could assign restricted credentials that only allow for DNS management in the respective domains and assign them to the workspace. Then there should be no doubt on what credentials are being used, and those credentials won't have access to do anything else.

More complex infrastructure management patterns generally dictate this kind of setup, following a "principle of least privilege" model. It's of out of scope for what we're discussing here, but it might be worth looking into for you so you can untangle and better audit the "what" and "why" of your infrastructure management strategy.

Cheers!

**Comment by stdedos** [comment]
Thank you for the suggestion -- I get the "principle of least privilege" principle. Where I'm stuck is the bootstrapping: the same Terraform that would consume those scoped DNS-only credentials is also the one that would provision them. So I end up in a loop.

And on the trust side: if a compromised provider is running in my workspace, it can already read whatever is in the environment -- I think additional scoped credentials won't change the blast radius much at that point. The real boundary seems to be "do I trust the providers I'm pulling in," not "how narrow are the credentials I pass them" - since both of them execute "at the same level".

I might be wrong on this -- I've been going in circles on this infra setup until it started working, which is when I came on this issue / to lego 😅 (~50 applies deep at this point)

<img width="477" height="640" alt="Image" src="https://github.com/user-attachments/assets/0e15625b-fba4-41ed-bf3a-e702d9469e6b" />

Thank you for the knowledge nuggets 😊
