### ISSUE TITLE
Wildcard certificate support using manual verification

### ISSUE THREAD

**Issue by ravikadam** [vancluever/terraform-provider-acme#442]
I am on GoDaddy domain and they have stopped API access to owners with less than 50 domains. I still wanted to do wildcard certificate generation via Terraform. Can I give provider as "manual" and Terraform can prompt with me DNS challenge and I can complete it. Is there any way to do it. Please help if you can. Thank You

**Comment by vancluever** [comment]
Hey @ravikadam, the best thing I can recommend is try the [exec](https://registry.terraform.io/providers/vancluever/acme/latest/docs/guides/dns-providers-exec) provider and see if you can swing some sort of shell script that would allow you to swing something in a long-lived process way. Otherwise we do not support the manual provider (as seen in lego) and don't plan to. Sorry!

**Comment by ravikadam** [comment]
> Hey @ravikadam, the best thing I can recommend is try the [exec](https://registry.terraform.io/providers/vancluever/acme/latest/docs/guides/dns-providers-exec) provider and see if you can swing some sort of shell script that would allow you to swing something in a long-lived process way. Otherwise we do not support the manual provider (as seen in lego) and don't plan to. Sorry!

Thank you. I shall try exec provider
