### ISSUE TITLE
Azurerm 4.4.0 : dependencies update for github.com/hashicorp/go-azure-sdk

### ISSUE THREAD

**Issue by kjetilcapgemini** [vancluever/terraform-provider-acme#444]
Hello
Need som help on an error I am getting when using the acme provider with Terraform, deploying to Azure
The error I get is the same as in "azuredns: could not find zone (from discovery) #428."
But I have values in the dns challenge config block like this:
config = {

      AZURE_AUTH_METHOD     = "env"
      AZURE_ENVIRONMENT     = "public"
      AZURE_CLIENT_ID       = data.azurerm_client_config.current.client_id
      AZURE_SUBSCRIPTION_ID = "11111111-1111-1111-1111-111111111111"
      AZURE_TENANT_ID       = data.azurerm_client_config.current.tenant_id
      AZURE_RESOURCE_GROUP  = data.azurerm_resource_group.rg.name
      AZURE_ZONE_NAME       = each.value.name
      AZURE_TTL             = 300
    }

The service principal running the terraform plan and apply has the correct rbac on subscription(contributor), resource group(dns zone admin) and dns zones.

I turned on debuging in Terraform and I notice this warning:
2024-10-26T12:25:48.119Z [WARN]  Provider "registry.terraform.io/vancluever/acme" produced an invalid plan for acme_certificate.cert["domain_name"], but we are tolerating it because it is using the legacy plugin SDK.

I then started to look through the azurerm changelog:https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md.
version 4.4.0 (october 04,2024) there is a dependencies update for github.com/hashicorp/go-azure-sdk

I am no programer, but could it be that the acme provider needs to use the new sdk?

I have been strugeling with this for the last two days and have tried everything, but still no luck
I am on the following versions:
Terraform: 1.9.8
Acme: 2.26.0
Azurerm: 4.7.0 (started at 3.166.0)

Here is the error message that Terraform gives me:
Error: error creating certificate: error: one or more domains had a problem:
│ [domain.com] [domain.com] acme: error presenting token: 2 errors occurred:
│ 	* rpc error: code = Unknown desc = azuredns: could not find zone (from discovery): domain.com
│ 	* error encountered while presenting token for DNS challenge: rpc error: code = Unknown desc = azuredns: could not find zone (from discovery): domain.com

Regards 
Kjetil

**Comment by vancluever** [comment]
Hey @kjetilcapgemini sorry for the delay in replying!

Answers inline:

> I turned on debuging in Terraform and I notice this warning:
> `2024-10-26T12:25:48.119Z [WARN] Provider "registry.terraform.io/vancluever/acme" produced an invalid plan for acme_certificate.cert["domain_name"], but we are tolerating it because it is using the legacy plugin SDK.`

This is just a warning that the provider uses the old Terraform Plugin SDK. It still works, so we still use it. 🤷‍♂️ 😉 
This is just a red herring to your issue though, so no worries on that.

The more particular error here is:

```
azuredns: could not find zone (from discovery): domain.com
```

This indicates that the domain you're working with isn't visible from the service principal that you're using with the provider.

Have you been able to confirm that you can see it from the appropriate principal via other means, e.g., CLI or what not?

> I am no programer, but could it be that the acme provider needs to use the new sdk?

As mentioned, on the TF side, using the legacy SDK is fine (and we'd see a lot more noise if it wasn't and we'd be upgrading pretty quickly).

On the _Azure_ side, since we integrate with `[lego](https://github.com/go-acme/lego)`, we follow what they do in terms of SDK dependencies. AFAIK, there's no issues on that side; additionally, again, if there were general SDK compatibility issues we'd probably have seen more issues about it here.

The best way forward will probably be that you can confirm that you can see the domain from the principal that you've created.

Hope this helps, and let me know how you do!

**Comment by kjetilcapgemini** [comment]
@vancluever thank you for the feedback.  I came to the same conclusion. This is not an issue with the SDK, since there where nobody else complaining.
 I successfully logged into powershell with the principal and created a TXT record and deleted it.
 I also confirmed by setting up a local Terraform configuration and got the certificate.

 In my Azure devops certificate apply task I had the arm_use_oidc environment variable set to true and I also applied the arm_client_secret environment variable in the same apply task.
I am using oidc auth on other azure devops tasks (create dns zones)in the same pipeline.
When I removed arm_use_oidc in the certificate apply task and only used arm_client_secret variable it worked
 
 I also tried to use oidc in the acme_certificate terraform resource, but could not get it to work.
Terraform gives me this message: OIDCToken, OIDCTokenFilePath or OIDCRequestURL and OIDCRequestToken must be set. I guess this is something that is implemented in the Lego Azure dns provider, but I could not find any documentation on how to set it up. I will stick with azure_auth_method = env in the acme_certificate terraform resource

Regards
K

**Comment by vancluever** [comment]
@kjetilcapgemini just wanted to send a note and say glad you figured it out! Just a note if you have the time and the resources you can try testing on the lego CLI itself. We a document on testing in brief [here](https://github.com/vancluever/terraform-provider-acme/blob/main/docs/lego.md).

Thanks!
