### ISSUE TITLE
Switching provider server_url raises 404 error

### ISSUE THREAD

**Issue by JordanP** [vancluever/terraform-provider-acme#88]
So, I tried the provider with the "https://acme-staging-v02.api.letsencrypt.org/directory" server_url. Created a registration and a cert, all is fine. Now I want to use the real thing, so I use the real letsencrypt url. But "terraform apply" fails with
```
module.certificates.acme_registration.reg: Destroying... [id=https://acme-v02.api.letsencrypt.org/acme/acct/65536822]
module.certificates.acme_certificate.certificate: Destroying... [id=https://acme-staging-v02.api.letsencrypt.org/acme/cert/fa393f4a5dcb98b363502cea7d39847580fb]
module.certificates.acme_registration.reg: Destruction complete after 1s
module.certificates.tls_private_key.reg_private_key: Destroying... [id=7584ae844a75c15ec019d6a19ea4e803c5fc4645]
module.certificates.tls_private_key.reg_private_key: Destruction complete after 0s

Error: acme: error: 404 :: POST :: https://acme-v02.api.letsencrypt.org/acme/revoke-cert :: urn:ietf:params:acme:error:malformed :: No such certificate, url: 
```
It looks like it tried to delete the previous certificate but using the new server_url...so the server replies "not found".

I think it's safe to ignore a 404 error on a delete operation: certificate is unknown/deleted, which is what we wanted in the first place

**Comment by StephenWithPH** [comment]
We were doing something very similar and observed the following behavior:

1. We had created an `acme_registration` and `acme_certificate` using Let's Encrypt's staging url.
1. We switched the provider to use Let's Encrypt's production url.
1. `terraform plan` -> `terraform apply` created a new `acme_registration` and did nothing with the previously-created `acme_registration` and `acme_certificate` which had been creating using the staging url:
    ```hcl
      # module.certificate.acme_registration.this will be created
      + resource "acme_registration" "this" {
          + account_key_pem  = (sensitive value)
          + email_address    = <redacted>
          + id               = (known after apply)
          + registration_url = (known after apply)
        }
    ```
1. We discovered that the resources tied to the staging url were still around, so we manually tainted them using `terraform taint`.
1. `terraform plan` showed that it needed to re-create the two resources.
1. `terraform apply` failed while trying to destroy the existing resources due to url issues (this cert was created on their staging url but the provider is now configured to use their production url):
    ```sh
    Error: acme: error: 404 :: POST :: https://acme-v02.api.letsencrypt.org/acme/revoke-cert :: urn:ietf:params:acme:error:malformed :: No such certificate, url: 
    ```

## Possible Solution

I __think__ this might be solvable using the [`ForceNew`](https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#forcenew) schema behavior on [`server_url`](https://github.com/terraform-providers/terraform-provider-acme/blob/master/acme/provider.go#L13) combined with recording the server url which "owns" the certificate on the resources themselves.

I couldn't find a quick example of using this behavior on _Provider_ attributes; perhaps recording the url on the resource might be sufficient.

**Comment by ttfjustin** [comment]
Another possible solution is to remove the items from the state file. We ran:

terraform state rm module.testwise-productscoring.acme_certificate.certificate
terraform state rm module.testwise-productscoring.acme_registration.reg

then re-ran the terraform code which successfully created a new staging certificate. We had swapped to prod for testing purposes and failed to read the warning.

**Comment by ttfjustin** [comment]
We fixed this problem by removing the items from the terraform state file by running:

terraform state rm module.product.acme_certificate.certificate
terraform state rm module.product.acme_registration.reg

After this, the certificate generates correctly. We had to do this after swapping staging to production for testing purposes without reading the warning!

**Comment by vancluever** [comment]
Hey all, apologies for the highly delayed reply to this issue.

After evaluating some options here I've decided to leave functionality as-is. While it's easier to deal with already-deactivated registrations, certificates are a bit of a different story:

- Guidance for dealing with errors in revocation as per RFC 8555 ([7.6](https://tools.ietf.org/html/rfc8555#section-7.6)) is a but ambiguous, with no concrete differentiation between missing certificates and other errors like authorization errors. We can rely on Boulder, but...
- Additionally, this is hard to test as generally certificates are not deleted from a CA, they are _revoked_, meaning that we will get a different error when setting up the test case. Specifically, Boulder does send a [different error for revocation conflicts](https://github.com/letsencrypt/boulder/blob/ebba443cad233111ee2b769ef09b32a13c3ba57e/wfe/wfe.go#L885-L888) as it does for [missing certificates](https://github.com/letsencrypt/boulder/blob/ebba443cad233111ee2b769ef09b32a13c3ba57e/wfe/wfe.go#L851-L854).

As this generally happens when switching URLs and code between staging and production environments, what I would just suggest is that folks make use of different workspaces to make sure these problems are generally avoided, and if you have to use the same workspace, make sure you destroy your staging resources before you switch to a production directory.

Thanks!

**Comment by byteknacker** [comment]
I ran into the same issue. It also does not work as expected when you have an aliased provider for acme. When I using acme.prod provider alias for example, it just does not delete the staging cert and creates a new production cert. I guess right now I have to just delete them manually from the statefile.

**Comment by chiefy** [comment]
Just ran into this myself, might be handy to at least update the docs to make note you have to remove the staging state before trying to generate a prod cert.
